// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: LinkedModel.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright (c) 2019, Apple Inc. All rights reserved.
//
// Use of this source code is governed by a BSD-3-clause license that can be
// found in LICENSE.txt or at https://opensource.org/licenses/BSD-3-Clause

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///
/// A model which wraps another (compiled) model external to this one
public struct LinkedModel {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var linkType: LinkedModel.OneOf_LinkType? = nil

  /// A model located via a file system path
  public var linkedModelFile: LinkedModelFile {
    get {
      if case .linkedModelFile(let v)? = linkType {return v}
      return LinkedModelFile()
    }
    set {linkType = .linkedModelFile(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_LinkType: Equatable {
    /// A model located via a file system path
    case linkedModelFile(LinkedModelFile)

  #if !swift(>=4.1)
    public static func ==(lhs: LinkedModel.OneOf_LinkType, rhs: LinkedModel.OneOf_LinkType) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.linkedModelFile, .linkedModelFile): return {
        guard case .linkedModelFile(let l) = lhs, case .linkedModelFile(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      }
    }
  #endif
  }

  public init() {}
}

/// Model is referenced by a model file name and search path
public struct LinkedModelFile {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Model file name: e.g. "MyFetureExtractor.mlmodelc"
  public var linkedModelFileName: StringParameter {
    get {return _linkedModelFileName ?? StringParameter()}
    set {_linkedModelFileName = newValue}
  }
  /// Returns true if `linkedModelFileName` has been explicitly set.
  public var hasLinkedModelFileName: Bool {return self._linkedModelFileName != nil}
  /// Clears the value of `linkedModelFileName`. Subsequent reads from it will return its default value.
  public mutating func clearLinkedModelFileName() {self._linkedModelFileName = nil}

  /// Search path to find the linked model file
  /// Multiple paths can be searched using the unix-style path separator ":"
  /// Each path can be relative (to this model) or absolute
  ///
  /// An empty string is the same as the relative search path "."
  /// which searches in the same location as this model file
  ///
  /// There are some special paths which start with $
  /// - $BUNDLE_MAIN - Indicates to look in the main bundle
  /// - $BUNDLE_IDENTIFIER(identifier) - Looks in Bunde with given identifier
  public var linkedModelSearchPath: StringParameter {
    get {return _linkedModelSearchPath ?? StringParameter()}
    set {_linkedModelSearchPath = newValue}
  }
  /// Returns true if `linkedModelSearchPath` has been explicitly set.
  public var hasLinkedModelSearchPath: Bool {return self._linkedModelSearchPath != nil}
  /// Clears the value of `linkedModelSearchPath`. Subsequent reads from it will return its default value.
  public mutating func clearLinkedModelSearchPath() {self._linkedModelSearchPath = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _linkedModelFileName: StringParameter? = nil
  fileprivate var _linkedModelSearchPath: StringParameter? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension LinkedModel: @unchecked Sendable {}
extension LinkedModel.OneOf_LinkType: @unchecked Sendable {}
extension LinkedModelFile: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "CoreML.Specification"

extension LinkedModel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinkedModel"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "linkedModelFile"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: LinkedModelFile?
        var hadOneofValue = false
        if let current = self.linkType {
          hadOneofValue = true
          if case .linkedModelFile(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.linkType = .linkedModelFile(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .linkedModelFile(let v)? = self.linkType {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: LinkedModel, rhs: LinkedModel) -> Bool {
    if lhs.linkType != rhs.linkType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LinkedModelFile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinkedModelFile"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "linkedModelFileName"),
    2: .same(proto: "linkedModelSearchPath"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._linkedModelFileName) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._linkedModelSearchPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._linkedModelFileName {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._linkedModelSearchPath {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: LinkedModelFile, rhs: LinkedModelFile) -> Bool {
    if lhs._linkedModelFileName != rhs._linkedModelFileName {return false}
    if lhs._linkedModelSearchPath != rhs._linkedModelSearchPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
